### ISSUE TITLE
reading Azure ad group members causes memory spike and crash => data "azuread_group" "example"

### ISSUE THREAD

**Issue by Sharmanand** [hashicorp/terraform-provider-azuread#1612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform Version 1.9.6
provider registry.terraform.io/hashicorp/azuread v3.0.2

### Affected Resource(s)

* `data.azuread_group.example`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

We have several groups managed by terraform. However after upgrading to v.3.02 it's taking time retrieve the group and using insane amount of memory.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by Sharmanand** [comment]
@mbfrahry can you please review?

**Comment by manicminer** [comment]
@Sharmanand Are you _sure_ you're using 3.0.2? This was fixed in that version (3.0.0 and 3.0.1 exhibit this issue).

**Comment by Sharmanand** [comment]
@manicminer yes i tried with v3.0.2. terraform plan also taking significant amount of time. v.2.5.3 was all good i tested against.

**Comment by Sharmanand** [comment]
@manicminer fyi. i checked last commit andfeel that they only fixed ad group resource (resource "azuread_group" "example") and issue still exist for ad group data resource(data "azuread_group" "example")
